# -*- coding: utf-8 -*-
"""nyc_shooting_vics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ymP0EWxgl1iapHB0oeePFM0-3WXoFr9F
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from matplotlib import pyplot
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import explained_variance_score, mean_squared_error, r2_score, mean_absolute_error
from collections import Counter
from keras import callbacks
import tensorflow as tf
from tensorflow.keras.layers import Dense, Dropout,InputLayer
from tensorflow.keras.models import Sequential
from keras.layers import BatchNormalization
from tensorflow.keras import regularizers
from tensorflow.keras import backend
from random import shuffle
from keras.callbacks import ModelCheckpoint
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.optimizers import RMSprop
import warnings
warnings.filterwarnings("ignore")

"""Let's import and get an overview of our data, this dayta relates to shootings in NYC"""

data=pd.read_csv('/content/NYPD_Shooting_Incident_Data__Historic_.csv')

data.head() #see a small sample of the data

#Information about the data
data.info()

"""Ok so LOC_CLASSFCTN_DESC  and LOC_OF_OCCUR_DESC are 90+% Null so no replacement can really be done! Drop them. I also will note that income is not present, this is an issue in my opinion as to me income and sociual group is far more important than age or race."""

# Commented out IPython magic to ensure Python compatibility.
# data.drop(['LOC_CLASSFCTN_DESC','LOC_OF_OCCUR_DESC'],axis=1,inplace=True)
# %%data source=https://catalog.data.gov/dataset?q=nyc+demographics&sort=views_recent+desc&tags=crime&ext_location=&ext_bbox=&ext_prev_extent=%%

data.head()

"""Let's look first at Boro and Percinct first"""

# function to create labeled barplots


def labeled_barplot(data, feature, perc=False, n=None):
    """
    Barplot with percentage at the top

    data: dataframe
    feature: dataframe column
    perc: whether to display percentages instead of count (default is False)
    n: displays the top n category levels (default is None, i.e., display all levels)
    """

    total = len(data[feature])  # length of the column
    count = data[feature].nunique()
    if n is None:
        plt.figure(figsize=(count + 1, 5))
    else:
        plt.figure(figsize=(n + 1, 5))

    plt.xticks(rotation=90, fontsize=15)
    ax = sns.countplot(
        data=data,
        x=feature,
        palette="Paired",
        order=data[feature].value_counts().index[:n].sort_values(),
    )

    for p in ax.patches:
        if perc == True:
            label = "{:.1f}%".format(
                100 * p.get_height() / total
            )  # percentage of each class of the category
        else:
            label = p.get_height()  # count of each level of the category

        x = p.get_x() + p.get_width() / 2  # width of the plot
        y = p.get_height()  # height of the plot

        ax.annotate(
            label,
            (x, y),
            ha="center",
            va="center",
            size=12,
            xytext=(0, 5),
            textcoords="offset points",
        )  # annotate the percentage

    plt.show()  # show the plot

labeled_barplot(data, "BORO", perc=True)

"""So 40% of shootings occur in Brooklyn while making about 30% of the population. Staten Island is the lowest in both regard making 2,8% of shootings and about 6% of the population. At the moment it is irresponsible to assume this is significant. I will create a new data frame based on the data found here:https://www.citypopulation.de/en/usa/newyorkcity/

"""

data_bb=[['BRONX',1379946],['BROOKLYN',2590516],['MANHATTAN',1596273],['QUEENS',2278029],['STATEN ISLAND',491133]]
data2=pd.DataFrame(data=data_bb, columns=['Boro','Population'])

total_pop=data2['Population'].sum()
total_pop
perc=data2['Population']/total_pop*100
data2['Percent']=perc

ax=data2.plot.bar(x='Boro',y="Percent",rot=0)
for container in ax.containers:
  ax.bar_label(container)

"""Bronx and Brooklyn appear to make up a higher  percentage of murders than population, while the reverse is true of Manhattan and Queens and Staten.

For PRECINCT I will create a mini data set for each BORO, I am not an expert on NYC but my understanding is each PRECINCT can be in one BORO and this will help visualize it more easily
"""

BRONX_data=data.query('BORO=="BRONX"')
BRONX_data.head()

labeled_barplot(BRONX_data, "PRECINCT", perc=True)

"""40,44,46, and 47 all have above 10+% of shootings here. I will in the future try to find precinct level data for population"""

BROOKLYN_data=data.query('BORO=="BROOKLYN"')
BROOKLYN_data.head()

labeled_barplot(BROOKLYN_data, "PRECINCT", perc=True)

"""73 and 75 have very high number of shootings, 67 is close behind, 74 seems to be missing"""

MANHATTAN_data=data.query('BORO=="MANHATTAN"')
MANHATTAN_data.head()

labeled_barplot(MANHATTAN_data, "PRECINCT", perc=True)

"""A number of precincts appear missing, those with higher numbers seem to have more shootings"""

QUEENS_data=data.query('BORO=="QUEENS"')
QUEENS_data.head()

labeled_barplot(QUEENS_data, "PRECINCT", perc=True)

"""118 has a lot of shootings while some have bet to none"""

STATEN_data=data.query('BORO=="STATEN ISLAND"')
STATEN_data.head()

labeled_barplot(STATEN_data, "PRECINCT", perc=True)

"""Almost 3/4 of all shootings in Staten island happend in 120

I would now like to look at personal factors of victims, though again I would have liked class data we will settle for race, age, and gender
"""

labeled_barplot(data, "VIC_AGE_GROUP", perc=True)

"""According to the census 16.8% of NYC is under 18, this is higher than reported victims suggesting  they are less likely to be shot,with ther rate of them being shot being roughly 62% of their population Seems like a good outcome though the fact over 10% of victims are kids is disturbing still

18-24 years olds make up a mere 10.2% of the population meaning they are 3.75 times more likely than rnadom to be victims of a shooting.

25-44 years olds are 38.3% of the population so the rate of shotoing were they are the victims roughly lines up with their population, the icnreas ebeing about 14%

45-64 years olds are 22.6% of the population, meaning they are much less liekly to be shot than random with the rate of shototing being 39% of the percent of their population

65+ years olds are even more skewed with a population percenatge  of 12.2% they are 17.5 times LESS liklely to be shot than random

There is a weird 1022 data point here, I assume this is a typo so lets drop it and chekc again
"""

data=data.drop(data[data['VIC_AGE_GROUP']=='1022'].index)
labeled_barplot(data, "VIC_AGE_GROUP", perc=True)

"""I will do gender next"""

labeled_barplot(data, "VIC_SEX", perc=True)

"""A few points to note, the data seems to use biological sex so this can not be used to look at data like trans gender related violence and there are, as always, a few unknowns. I am not sure if these people were missing certain parts that would make that disctinction or if perhaps no victim was found, may be worth checking out if possible,

That said men make up 48% of the population but over 90% of shooting victims, so it may be worth exploring the relationship between gender and violence when given more detailed data
"""

labeled_barplot(data, "VIC_RACE", perc=True)

"""Nothing against Asain, Native, or unknown indivudals but let us focus first on white vs. black vs. hispanic. Acocridng again to the census 28.7% of NYC identifies as Hispanic and if we combine the two hispanic cateogries here we get 25.5% meaning they are roughly 89% as likely (11% LESS likely) to be shot compared to random. I will point out that self idenitfying as Hispanic on the census may be different than the way the police defines Hispanic. This same logic can and should be used on race in general and possibly sex, depening of the context

"Black", more properly African America I think, individuals make up only 20.2% of the population but 71.2% of shooting victims. These means they are over 3 times as likely to be shot as random.

White, by which amay include European; middle eastern; and maybe even Indian (country) whites make up 30,9% of the population but only 2.6% of victims. this means they are  91.5% less likely than random to be victims.

When comparing these numbers it becomes clear there is a major issue in NYC in dealing with crimes against POC, though without soceconomic data I cna't even begin to say why.

I will now look at the interaction between race, gender, and age
"""

def stacked_barplot(data, predictor, target):#better for comparing cateogries
    """
    Print the category counts and plot a stacked bar chart

    data: dataframe
    predictor: independent variable
    target: target variable
    """
    count = data[predictor].nunique()
    sorter = data[target].value_counts().index[-1]
    tab1 = pd.crosstab(data[predictor], data[target], margins=True).sort_values(
        by=sorter, ascending=False
    )
    print(tab1)
    print("-" * 120)
    tab = pd.crosstab(data[predictor], data[target], normalize="index").sort_values(
        by=sorter, ascending=False
    )
    tab.plot(kind="bar", stacked=True, figsize=(count + 5, 6))
    plt.legend(
        loc="lower left", frameon=False,
    )
    plt.legend(loc="upper left", bbox_to_anchor=(1, 1))
    plt.show()

stacked_barplot(data, "VIC_RACE","VIC_SEX")

"""As I suspected the majority of unknown gender are also unknown race, though a good number are also African American.

Most races have women making about 10% of the vicitm pool though whites it is above 16%, these MAY suggect a difference in cause of violence amongts races but I would need more details to suggest a cause or even prove one exists
"""

stacked_barplot(data, "VIC_AGE_GROUP","VIC_SEX")

"""Again unknown seems to be more common with unknown, again suggesting the victim was not known to police.
Interstingly, women make up a larger percentage of the victim pool at ages above 45 and below 18, again suggesting the possibility of differences in victimology
"""

stacked_barplot(data, "VIC_RACE","VIC_AGE_GROUP")

"""Again, unknown is comon with other unknwon.
Natives and the asain groupo where low, but it is interesting no victims above 44 existed in the Native populus.

There do appear ot be more older victims amonst white citizens than other groups
"""